mainApplication/urls.py
from . import views
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    # path('', views.index, name='root'),  # Esto manejará /registrationSystem/
    path('',views.index,name='index'),
    path('dashboard/',views.dashboard,name="dashboard"),
    path('completeProfile/',views.complete_profile,name="complete_profile"),
    path('payment/',views.payment,name="payment"),
    path('schedule/',views.schedule,name="schedule"),
    path('schedulePublic/',views.schedulePublic,name="schedulePublic"),
    path('validatePayment/',views.validPay,name="validatePayment"),
    path('registerintoEvent/', views.registerintoEvent, name='registerintoEvent'),
    path('seeSchedule/', views.seeMySchedule, name='seeMySchedule'),
    path('seeDiplomas/', views.seeMyDiplomas, name='seeMyDiplomas'),
    path('sentDiploma/<int:event_id>', views.generateMyDiplomas, name='sentDiploma'),
    path('assist/<int:user_id>/<int:registration_id>/', views.assistanceControl, name='assistanceControl'),#admin/staff
    path('welcomeKit/<int:user_id>/', views.welcomeKit, name='welcomeKit'),#admin/staff control de kits de bienvenida
    path('registerPlace/', views.register_place, name='registerPlace'),#admin/staff
    path('registerStaff/', views.registerStaff, name='registerStaff'),#admin/staff
    path('registerEvent/', views.register_event, name='registerEvent'),#admin/staff
    path('edit-event/<int:event_id>/', views.edit_event, name='editEvent'),#admin/staff
    path('delete-event/<int:event_id>/', views.delete_event, name='deleteEvent'),#admin/staff
    path('events/', views.list_events, name='listEvents'),#admin/staff
    path('manageCongressDates/', views.manage_congress_dates, name='manageCongressDates'),#admin/staff
    path('editCongressDate/<int:date_id>/', views.edit_congress_date, name='editCongressDate'),#admin/staff
    path('deleteCongressDate/<int:date_id>/', views.delete_congress_date, name='deleteCongressDate'),#admin/staff
    path('checkAssistance/', views.assistanceList, name='assistanceList'),#admin/staff
    path('validatePaymentAdmin/',views.validatePayment,name="validatePaymentAdmin"),#admin/staff
    path('kitAlreadyReceived/', views.kitAlreadyReceived,name="kitAlreadyReceived"),#admin/staff
    path('kitReceivedSuccessfully/', views.kitReceivedSuccessfully,name="kitReceivedSuccessfully"),#admin/staff
    path('consultWelcomeKit/', views.listarRecibioKit, name='consultWelcomeKit'),#admin/staff
    path('scholarshipAssignations/', views.scholarshipAssignations, name='scholarshipAssignations'),#admin/staff
    path('upload-banner/', views.upload_banner, name='upload_banner'),#para subir archivos
    path('delete-banner/<str:filename>/', views.delete_file_Banner, name='delete_file'),#para borrar archivos del banner
    path('topicsArea/', views.topics, name='topicsArea'),#para borrar archivos del banner
    # path('topicsAreaUpdate/<int:pk>/', TopicAreaUpdateView.as_view(), name='topic_area_update'),  # Editar TopicArea
    path('topicsAreaDelete/<int:pk>/', views.deleteTopics, name='topicsAreaDelete'),  # Eliminar TopicArea
    path('topicsAreaEdit/<int:pk>/', views.editTopic, name='topicsAreaEdit'),  # Editar TopicArea
    path('makeSubmission/', views.submitArticle, name='makeSubmission'),  # Hacer una nueva Submission
    path('mySubmissions/', views.seeMySubmissions, name='seeMySubmissions'),  # Hacer una nueva Submission
    path('editSubmission/<int:submissionID>/', views.editSubmission, name='editSubmission'),#Editar una Submission
    path('delete-file/<int:file_id>/', views.delete_file, name='delete_file'),
    path('withdraw/<str:submission_id>/', views.withdraw_submission, name='withdrawSubmission'),
    path('inviteReviewers/', views.inviteReviewers, name='inviteReviewers'),#inviteReviewers
    path('becomeReviewer/<str:code_hash>', views.becomeReviewer, name='becomeReviewer'),#becomeReviewer
    path('inviteReviewers/', views.inviteReviewers, name='inviteReviewers'),#inviteReviewers
    path('assignReviews/', views.assignReviews, name='assignReviews'),#assignReviews
    path('revertToDraftStatus/<int:submission_id>', views.revertToDraftStatus, name='revertToDraftStatus'),#revertToDraftStatus
    path('listSubmissions/', views.listSubmissions, name='listSubmissions'),#revertToDraftStatus
    path('seeAssignedReviews/', views.seeAssignedReviews, name='seeAssignedReviews'),#seeAssignReviews
    path('assess/<int:submission_id>', views.assess, name='assess'),#Assess submission
    path('serve-file/<int:file_id>/', views.serve_file, name='serve_file'),#serve files
    path('systemSettings/', views.systemSettingsView, name='systemSettings'),#serve files
    path('generate_decision/<int:submission_id>/', views.generate_decision_letter, name='generate_decision'),
    path('scientific-committee-diploma/', views.generateScientificCommitteeDiplomas, name='scientific_committee_diploma'),
    path('manageNews/', views.newsManageView, name='newsManage'),
    
]
urlpatterns += staticfiles_urlpatterns() 

registroCIMPSProyecto/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls,name="administradorSuperPoderoso"),
    path('',include('mainApplication.urls')),
    path('accounts/', include('allauth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainApplication/models.py
import random
import string
from datetime import datetime, timedelta
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from django.conf import settings
from django.forms import ValidationError
from django_countries.fields import CountryField
from django.contrib.auth.models import AbstractUser
from django.db import models

from django.core.validators import MinValueValidator, MaxValueValidator

from django.db.models import Avg

from django.core.files.storage import FileSystemStorage


class CustomUser(AbstractUser):
    isReviewer = models.BooleanField(default=False)
    
    def __str__(self):
        return self.email



#####################

class UserProfile(models.Model):
    GENDER_CHOICES = (
        ('male', 'Male'),
        ('female', 'Female'),
    )
    
    USER_TYPE_CHOICES = (
        ('author', 'Author'),
        ('public', 'General Public'),
        ('student', 'Student'),
        # ('guest', 'Guest'),
        # ('other', 'Other'),
    )

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES)
    state = models.CharField(max_length=100)
    country = CountryField()
    university_name = models.CharField(max_length=255)
    university_address = models.CharField(max_length=255)
    user_type = models.CharField(max_length=20, choices=USER_TYPE_CHOICES)
    payment_completed=models.BooleanField(default=0)
    payment_observarions=models.CharField(default=" ",max_length=255,null=True, blank=True)
    transactionID=models.CharField(default=" ",max_length=255, null=True, blank=True)
    recibioKIT=models.BooleanField(default=False)
    permitirRegistro=models.BooleanField(default=False)
    FullName=models.CharField(max_length=255, blank=True, null=True, verbose_name="Full Name (The name you write will be the one under which your certificates will be issued)")  # Nombre completo
    manualPayment=models.BooleanField(default=False)
    amount=models.CharField(default=" ",max_length=255, null=True, blank=True)



    # paper_id = models.CharField(max_length=100, blank=True, null=True)  # ID del artículo
    # paper_name = models.CharField(max_length=255, blank=True, null=True)  # Nombre del artículo

    def __str__(self):
        return self.user.username

class PaymentProof(models.Model):
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)  # Link to the user
    file = models.FileField(upload_to='payment_proofs/')  # Directory where the file will be uploaded
    uploaded_at = models.DateTimeField(auto_now_add=True)
    rejected=models.BooleanField(default=False)


class Place(models.Model):
    name = models.CharField(max_length=255)
    capacity = models.PositiveIntegerField(default=0)  # Add capacity field

    def __str__(self):
        return self.name


class Event(models.Model):
    EVENT_TYPES = [
        ('ieee', 'IEEE Article'),
        ('springer', 'Springer Article'),
        ('keynote', 'Keynote'),
        ('lunch', 'Lunch'),
        ('workshop', 'Workshop'),
        ('other', 'Other'),
    ]
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True,max_length=5000)
    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    place = models.ForeignKey(Place, on_delete=models.CASCADE)
    event_type = models.CharField(max_length=50, choices=EVENT_TYPES, default="other")
    ponent_name = models.CharField(max_length=255, blank=True)
    affiliation = models.CharField(max_length=255, blank=True)
    moderator = models.CharField(max_length=255, blank=True)
    banner = models.ImageField(upload_to='event_banners/', blank=True, null=True)
    links=models.CharField(default=" ",max_length=255,null=True, blank=True,verbose_name="Links of online meeting: ")
    requisites=models.CharField(default=" ",max_length=1000,null=True, blank=True,verbose_name="Requisites: ")
    allEvent=models.BooleanField(default=False,verbose_name="This event last all the congress? ")
    fileDiplomas = models.FileField(upload_to='diplomasTemplates/',null=True,blank=True)  # Directory where the file will be uploaded
    def is_ready_for_certificate(self):
        # Combina la fecha y hora de finalización
        event_end_datetime = datetime.combine(self.date, self.end_time)
        # Calcula la hora que debe pasar después del evento
        ready_time = event_end_datetime + timedelta(hours=1)
        # Verifica si la hora actual es mayor o igual que la hora lista para la constancia
        return datetime.now() >= ready_time



    def __str__(self):
        return f"{self.title} ({self.get_event_type_display()}) - {self.ponent_name} - {self.affiliation}"

    
    
class Registration(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    assisted=models.BooleanField(default=False)
    counter=models.IntegerField(default=0)
    receivedDiploma=models.BooleanField(default=False)

    class Meta:
        unique_together = ('user', 'event')  # Ensure a user can register for an event only once

class CongressDate(models.Model):
    date = models.DateField(unique=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.date.strftime('%d %b %Y')

    class Meta:
        ordering = ['date']

class adminPermissions(models.Model):#for welcome kit
    kitBienvenida = models.BooleanField(default=False)#si hay o no
    kitBienvenidaAll = models.BooleanField(default=False)#si hay ¿se dara a todos?
    kitBienvenidaOnlyPayment = models.BooleanField(default=False)#sino se da a todos ¿solo a pagados?
    kitBienvenidaSchoolarships = models.BooleanField(default=False)#sino se da a todos ¿se da a becados?


class TopicArea(models.Model):
    """
    Represents a topic area that can be configured by a superuser.
    """
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

def generate_random_submission_id():
    while True:
        submission_id = ''.join(random.choices(string.digits, k=6))  # Genera un número aleatorio de 6 dígitos
        if not submission_id.startswith('0'):  # Verifica que no empiece con '0'
            return submission_id


class Submission(models.Model):
    """
    Represents a submission made by a user.
    """
    PUBLICATION_TYPES = [
        ('IEEE', 'IEEE'),
        ('Springer', 'Springer'),
        ('Other', 'Other'),
    ]

    DECISION_STATUSES = [
        ('pending', 'Pending'),
        ('rejected', 'Rejected'),
        ('minor_changes', 'Accepted with Minor Changes'),
        ('major_changes', 'Accepted with Major Changes'),
        ('accepted', 'Accepted'),
    ]
    

    submission_id = models.CharField(max_length=6, unique=True, default=generate_random_submission_id)

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='submissions')
    title = models.CharField(max_length=255)
    publication_type = models.CharField(max_length=50, choices=PUBLICATION_TYPES)
    topic_areas = models.ManyToManyField(TopicArea, related_name='submissions')
    keywords = models.TextField(help_text="Comma-separated keywords.")
    abstract = models.TextField()
    comments = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    sent_for_review = models.BooleanField(default=False)
    reviewers = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='assigned_submissions',
        blank=True
    )  # Many-to-many relationship with reviewers
    is_withdrawn=models.BooleanField(default=False)
    assigned_reviewers=models.BooleanField(default=False)
    under_review = models.BooleanField(default=False)  # Status for being under review
    decision_issued = models.CharField(max_length=20,choices=DECISION_STATUSES,default='pending')  # Status for final decision issued

    final_decision = models.CharField(
        max_length=20,
        choices=DECISION_STATUSES,
        blank=True,
        null=True
    )  

    review_round = models.PositiveIntegerField(default=1)  # Round of review


    def __str__(self):
        return self.title
    
    def get_completed_reviews_count(self):
        """Returns the number of completed reviews for this submission."""
        return self.review_set.filter(review_completed=True).count()
    
    def get_total_reviews_count(self):
        """Returns the total number of assigned reviews."""
        return self.reviewers.count()
    
    def calculate_average_score(self):
        """
        Calculates the weighted average score from all completed reviews.
        Returns:
            - None if no completed reviews
            - Float score between 0 and 10 if reviews are completed
        """
        completed_reviews = self.review_set.filter(review_completed=True)
        
        if not completed_reviews.exists():
            return None
            
        # Calculate weighted scores for each completed review
        review_scores = [review.calculate_score() for review in completed_reviews if review.calculate_score() is not None]
        
        if not review_scores:  # Si no hay scores válidos después de filtrar None
            return None
            
        # Get the average score
        average_score = sum(review_scores) / len(review_scores)
        
        return round(average_score, 2)
    
    def get_review_summary(self):
        """
        Provides a detailed summary of the review recommendations.
        """
        completed_reviews = self.review_set.filter(review_completed=True)
        total_reviews = completed_reviews.count()
        

mainApplication/templates/editCongressDate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="container mt-4">
        <h2>Edit Congress Date</h2>
        
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                {{ form.date.label_tag }}
                {{ form.date }}
            </div>
            <div class="form-check mb-3">
                {{ form.is_active }}
                {{ form.is_active.label_tag }}
            </div>
            <button type="submit" class="btn btn-primary">Update Congress Date</button>
            <a href="{% url 'manageCongressDates' %}" class="btn btn-secondary">Cancel</a>
        </form>
    </div>
</body>
</html>

mainApplication/templates/editTopic.html
{% load static %}{% load socialaccount %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Topics Area - CIMPS</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'images/favicon.ico'%}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png'%}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css'%}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css'%}" rel="stylesheet">
  <link href="{% static 'assets/vendor/quill/quill.snow.css'%}" rel="stylesheet">
  <link href="{% static 'assets/vendor/quill/quill.bubble.css'%}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css'%}" rel="stylesheet">
  <link href="{% static 'assets/vendor/simple-datatables/style.css'%}" rel="stylesheet">
  

  <link href="{% static 'assets/css/style.css'%}" rel="stylesheet">
<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

<!-- Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>



</head>

<body>
  {% if messages %}
  <script>
    $(document).ready(function() {
      {% for message in messages %}
        // Aquí verificamos si el mensaje tiene una propiedad "level" para determinar su tipo
        {% if message.tags == "success" %}
          Swal.fire({
            title: 'Success!',
            text: "{{ message }}",
            icon: 'success',
            confirmButtonText: 'Ok'
          });
        {% elif message.tags == "error" %}
          Swal.fire({
            title: 'Error!',
            text: "{{ message }}",
            icon: 'error',
            confirmButtonText: 'Ok'
          });
        {% endif %}
      {% endfor %}
    });
  </script>
{% endif %}

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="{{request.scheme}}://{{ request.get_host }}/dashboard/" style="text-decoration: none;" class="logo d-flex align-items-center">
        <img src="{% static 'images/black_logo.png' %}" alt="">
        <span class="d-none d-lg-block">CIMPS {% now 'Y' %}</span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">

        

          


        

        <li class="nav-item dropdown pe-3">

          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            <img src="{{ user.socialaccount_set.all.0.get_avatar_url }}" alt="Profile" class="rounded-circle">
            <span class="d-none d-md-block  ps-2">Hi, {{ user.socialaccount_set.all.0.extra_data.name }}</span>
          </a><!-- End Profile Iamge Icon -->

          
        </li><!-- End Profile Nav -->

      </ul>
    </nav><!-- End Icons Navigation -->

  </header><!-- End Header -->

    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar">

      <ul class="sidebar-nav" id="sidebar-nav">
  
        <li class="nav-item">
          <a class="nav-link collapsed" href="{% url 'complete_profile'%}">
            <i class="bi bi-person"></i>
            <span>Profile Information</span>
          </a>
        </li>
        <li class="nav-item"></li>
          <a class="nav-link " href="{% url 'dashboard' %}">
            <i class="bi bi-grid"></i>
            <span>Dashboard</span>
          </a>
        </li>
        <li class="nav-item"></li>
        <a class="nav-link collapsed" href="{% url 'payment' %}">
            <i class="bi bi-cash-coin"></i>
            <span>Payment</span>
          </a>
        </li>
        <li class="nav-item"></li>
      <a class="nav-link collapsed" href="{% url 'schedule' %}">
        <i class="bi bi-calendar"></i>
        <span>Schedule (Program)</span>
      </a>
      <li class="nav-item"></li>
      <a class="nav-link collapsed" href="{% url 'seeMySchedule' %}">
        <i class="bi bi-file-earmark-break"></i>
        <span>See my schedule</span>
      </a>
    </li>
    <li class="nav-item"></li>
          <a class="nav-link collapsed" href="{% url 'seeMyDiplomas' %}">
            <i class="bx bxs-certification"></i>
            <span>My Diplomas</span>
          </a>
        </li>
        <li class="nav-item"></li>
          <a class="nav-link collapsed" href="{% url 'account_logout' %}">
            <i class="bi bi-door-closed-fill"></i>
            <span>Log Out</span>
          </a>
        </li>
        {% if userType.get_user_type_display == "Author" %}
        <li class="nav-item">Author Menu</li>
          <a class="nav-link collapsed" href="{{request.scheme}}://{{ request.get_host }}/admin">
            <i class="bi bi-journal-text"></i>
            <span>Submit an Article</span>
          </a>
        </li>
        <li class="nav-item"></li>
          <a class="nav-link collapsed" href="{{request.scheme}}://{{ request.get_host }}/admin">
            <i class="bi bi-calendar-check"></i>
            <span>My Submissions</span>
          </a>
        </li>
        
        {% endif %}
        {% if is_staff_user %}
        <li class="nav-item">Staff options</li>
          <a class="nav-link collapsed" href="{% url 'assistanceList' %}">
            <i class="bi bi-check2-square"></i>
            <span>Assistance List (Events)</span>
          </a>
        </li>
        <li class="nav-item"></li>
          <a class="nav-link collapsed" href="{% url 'scholarshipAssignations' %}">
            <i class="bi bi-mortarboard"></i>
            <span>Scholarship assignations</span>
          </a>
        </li>
        <li class="nav-item"></li>
          <a class="nav-link collapsed" href="{% url 'consultWelcomeKit' %}">
            <i class="bi bi-box2-heart"></i>
            <span>Welcome Kit Control</span>
          </a>
        </li>
        <li class="nav-item"></li>
          <a class="nav-link collapsed" href="{% url 'validatePaymentAdmin' %}">
            <i class="bi bi-wallet2"></i>
            <span>Validate Payments</span>
          </a>
        </li>
        
        {% endif %}
        
        {% if is_staff_superuser %}
        <li class="nav-item">Super Admin options</li>
          <a class="nav-link collapsed" href="{{request.scheme}}://{{ request.get_host }}/admin">
            <i class="bi bi-terminal"></i>
            <span>Super Admin Console</span>
          </a>
        </li>
        <li class="nav-item"></li>
          <a class="nav-link collapsed" href="{% url 'upload_banner' %}">
            <i class="bi bi-image"></i>
            <span>Configure gallery</span>
          </a>
        </li>
        <li class="nav-item"></li>
          <a class="nav-link collapsed" href="{% url 'registerStaff' %}">
            <i class="bi bi-file-earmark-person-fill"></i>
            <span>Register Staff members</span>
          </a>
        </li>
        <li class="nav-item"></li>
          <a class="nav-link collapsed" href="{% url 'registerPlace' %}">
            <i class="bi bi-building"></i>
            <span>Register Places</span>
          </a>
        </li>
        <li class="nav-item"></li>
          <a class="nav-link collapsed" href="{% url 'registerEvent' %}">
            <i class="bi bi-briefcase"></i>
            <span>Register Events</span>
          </a>
        </li>
        <li class="nav-item"></li>
          <a class="nav-link collapsed" href="{% url 'listEvents' %}">
            <i class="bi bi-card-list"></i>
            <span>List Events</span>
          </a>
        </li>
        <li class="nav-item"></li>
          <a class="nav-link collapsed" href="{% url 'manageCongressDates' %}">
            <i class="bi bi-calendar-check"></i>
            <span>Manage Congress Dates</span>
          </a>
        </li>
        {% endif %}
        
      </ul>
  
    </aside><!-- End Sidebar-->

  <main id="main" class="main">

    <div class="pagetitle">
      <h1>Topic Areas</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="#" style="text-decoration: none;">Home</a></li>
          <li class="breadcrumb-item active"><a href="#" style="text-decoration: none;">Topic Areas</a></li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <section class="section dashboard">
      <div class="row">
        <div class="col-lg-12">
          <div class="row">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Topic Area Edition</h5>
                
                
                <div class="container mt-4">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Save changes</button>
                        <a href="{% url 'topicsArea' %}" class="btn btn-secondary">Cancel</a>
                    </form>
                </div>
                
              </div>            
            </div>          
        </div>
      </div>
    </section>
    
  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">
    <div class="copyright">
      &copy; Copyright <strong><span>CIMAT</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
      <!-- All the links in the footer should remain intact. -->
      <!-- You can delete the links only if you purchased the pro version. -->
      <!-- Licensing information: https://bootstrapmade.com/license/ -->
      <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
      Developed by MSwE. Victor Miguel Terrón Macias
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/apexcharts/apexcharts.min.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/chart.js/chart.umd.js' %}"></script>
  <script src="{% static 'assets/vendor/echarts/echarts.min.js' %}"></script>
  <script src="{% static 'assets/vendor/quill/quill.js' %}"></script>
  <script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
  <script src="{% static 'assets/vendor/tinymce/tinymce.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>